#!/bin/python3
# just messing around, you can use python -c for this
import click
from io import StringIO

@click.command()
@click.option('--verbose', '-v', is_flag=True, help="Print more output.")
@click.option("-c", default="print('No command supplied to pico')", help="Command to supply")
def run_command(c, verbose):
    if verbose:
        print(f"!pico verbose!")
        print(f"Running command `{c}`")
    #with StringIO(c) as f:
    #    for line in f.readlines():
    #        print(line)
    c = c.split(r"\n")
    print(c)
    #print(c)
    #exec(c)


if __name__ == "__main__":
    run_command()