#!/bin/python3

import click

@click.command()
@click.option('--verbose', '-v', is_flag=True, help="Print more output.")
@click.option("-c", default="print('No command supplied to pico')", help="Command to supply")
def run_command(c, verbose):
    if verbose:
        print(f"!pico verbose!")
        print(f"Running command `{c}`")
    exec(c)


if __name__ == "__main__":
    run_command()